using System;
using System.Collections.Generic;
using System.Text;

using System.IO;

using Microsoft.VisualStudio.TestTools.UnitTesting;
using Rocket.PdfGenerator;

namespace Rocket.PdfGenerator.Tests
{
    [TestClass]
    public class GeneratePdfTests
    {
        const string HTML_CONTENT_COVER = "HTML COVER STRING";
        const string HTML_CONTENT = "Generated by <b>2go.space rocket pdf generator</b> with great tool <b>WKHtmlToPDF</b>";

        const string PDF_DIRECTORY = @"PDF\GeneratePdf";

        public GeneratePdfTests()
        {
            if (Directory.Exists(PDF_DIRECTORY) == false)
            {
                Directory.CreateDirectory(PDF_DIRECTORY);
            }
        }

        [TestMethod]
        public void GenerateByteArrayByString()
        {
            const string fileName = "GenerateByteArrayByString.pdf";

            HtmlToPdfConverter generator = new HtmlToPdfConverter();
            byte[] pdfByteArray = generator.GeneratePdf(HTML_CONTENT);

            File.WriteAllBytes(Path.Combine(PDF_DIRECTORY, fileName), pdfByteArray);

        }

        [TestMethod]
        public void GenerateByteArrayByStringAndCover()
        {
            const string fileName = "GenerateByteArrayByStringAndCover.pdf";

            HtmlToPdfConverter generator = new HtmlToPdfConverter();
            byte[] pdfByteArray = generator.GeneratePdf(HTML_CONTENT, HTML_CONTENT_COVER);

            File.WriteAllBytes(Path.Combine(PDF_DIRECTORY, fileName), pdfByteArray);
        }

        [TestMethod]
        public void GenerateStreamByStringAndCover()
        {
            const string fileName = "GenerateStreamByStringAndCover.pdf";

            using (MemoryStream stream = new MemoryStream())
            {
                HtmlToPdfConverter generator = new HtmlToPdfConverter();
                generator.GeneratePdf(HTML_CONTENT, HTML_CONTENT_COVER, stream);

                File.WriteAllBytes(Path.Combine(PDF_DIRECTORY, fileName), stream.ToArray());
            }
        }

        [TestMethod]
        public void GenerateFileByStringAndCover()
        {
            const string fileName = "GenerateFileByStringAndCover.pdf";

            HtmlToPdfConverter generator = new HtmlToPdfConverter();
            generator.GeneratePdf(HTML_CONTENT, HTML_CONTENT_COVER, Path.Combine(PDF_DIRECTORY, fileName));

        }
    }
}
